### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cbetta** [Sutto/rubyflow#1]
What is the license of this? Can I use this to make my own site focussed on a different topic?

**Comment by Sutto** [comment]
From the README: "All code developed by Peter Cooper within this project is in the public domain. Plugins, Rails, and derivative code is licensed as it was originally (mostly MIT)."

**Comment by Sutto** [comment]
(So yes, although this code is from an awful long time ago)

**Comment by cbetta** [comment]
Ah, in that case I'll poke Peter and see if he has a newer copy anywhere
